# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKUMARIBOOKSHOPCRUDOperationTesting():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_kUMARIBOOKSHOPCRUDOperationTesting(self):
    # Test name: KUMARI BOOKSHOP CRUD Operation Testing
    # Step # | name | target | value
    # 1 | open | /products | 
    self.driver.get("http://127.0.0.1:5000/products")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | linkText=ADD PRODUCT | 
    self.driver.find_element(By.LINK_TEXT, "ADD PRODUCT").click()
    # 4 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 5 | type | id=name | Colour Pen
    self.driver.find_element(By.ID, "name").send_keys("Colour Pen")
    # 6 | click | id=price | 
    self.driver.find_element(By.ID, "price").click()
    # 7 | type | id=price | 10
    self.driver.find_element(By.ID, "price").send_keys("10")
    # 8 | click | id=sprice | 
    self.driver.find_element(By.ID, "sprice").click()
    # 9 | type | id=sprice | 25
    self.driver.find_element(By.ID, "sprice").send_keys("25")
    # 10 | click | id=stock | 
    self.driver.find_element(By.ID, "stock").click()
    # 11 | type | id=stock | 100
    self.driver.find_element(By.ID, "stock").send_keys("100")
    # 12 | click | css=.btn-default | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    # 13 | click | css=tr:nth-child(9) button:nth-child(1) > a | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(9) button:nth-child(1) > a").click()
    # 14 | click | id=price | 
    self.driver.find_element(By.ID, "price").click()
    # 15 | type | id=price | 15
    self.driver.find_element(By.ID, "price").send_keys("15")
    # 16 | click | css=.btn-default | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    # 17 | click | css=tr:nth-child(9) button:nth-child(2) > a | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(9) button:nth-child(2) > a").click()
    # 18 | click | linkText=ADD CUSTOMER | 
    self.driver.find_element(By.LINK_TEXT, "ADD CUSTOMER").click()
    # 19 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 20 | type | id=name | Test Customer
    self.driver.find_element(By.ID, "name").send_keys("Test Customer")
    # 21 | click | id=nic | 
    self.driver.find_element(By.ID, "nic").click()
    # 22 | type | id=nic | 987456321
    self.driver.find_element(By.ID, "nic").send_keys("987456321")
    # 23 | click | id=adderss | 
    self.driver.find_element(By.ID, "adderss").click()
    # 24 | type | id=adderss | No 30 Ganegama Road
    self.driver.find_element(By.ID, "adderss").send_keys("No 30 Ganegama Road")
    # 25 | click | id=contact | 
    self.driver.find_element(By.ID, "contact").click()
    # 26 | type | id=contact | 0710132681
    self.driver.find_element(By.ID, "contact").send_keys("0710132681")
    # 27 | click | css=.btn-default | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    # 28 | click | css=tr:nth-child(5) button:nth-child(1) > a | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) button:nth-child(1) > a").click()
    # 29 | click | css=.container | 
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    # 30 | type | id=address | Ganegama Road
    self.driver.find_element(By.ID, "address").send_keys("Ganegama Road")
    # 31 | click | css=.btn-default | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    # 32 | click | css=tr:nth-child(5) button:nth-child(2) > a | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) button:nth-child(2) > a").click()
    # 33 | click | linkText=ADD EMPLOYEE | 
    self.driver.find_element(By.LINK_TEXT, "ADD EMPLOYEE").click()
    # 34 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 35 | type | id=name | Test employee
    self.driver.find_element(By.ID, "name").send_keys("Test employee")
    # 36 | click | id=nic | 
    self.driver.find_element(By.ID, "nic").click()
    # 37 | type | id=nic | 123456789v
    self.driver.find_element(By.ID, "nic").send_keys("123456789v")
    # 38 | type | id=nic | 123456789
    self.driver.find_element(By.ID, "nic").send_keys("123456789")
    # 39 | click | id=adderss | 
    self.driver.find_element(By.ID, "adderss").click()
    # 40 | type | id=adderss | Wennappuwa
    self.driver.find_element(By.ID, "adderss").send_keys("Wennappuwa")
    # 41 | click | id=contact | 
    self.driver.find_element(By.ID, "contact").click()
    # 42 | type | id=contact | 0710132681
    self.driver.find_element(By.ID, "contact").send_keys("0710132681")
    # 43 | click | css=.btn-default | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    # 44 | click | css=tr:nth-child(2) button:nth-child(1) > a | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) button:nth-child(1) > a").click()
    # 45 | click | id=nic | 
    self.driver.find_element(By.ID, "nic").click()
    # 46 | click | id=nic | 
    self.driver.find_element(By.ID, "nic").click()
    # 47 | doubleClick | id=nic | 
    element = self.driver.find_element(By.ID, "nic")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 48 | type | id=nic | 195874523
    self.driver.find_element(By.ID, "nic").send_keys("195874523")
    # 49 | click | css=.btn-default | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    # 50 | click | css=tr:nth-child(2) button:nth-child(2) > a | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) button:nth-child(2) > a").click()
    # 51 | click | linkText=ADD SUPPLIER | 
    self.driver.find_element(By.LINK_TEXT, "ADD SUPPLIER").click()
    # 52 | click | id=name | 
    self.driver.find_element(By.ID, "name").click()
    # 53 | type | id=name | Rathna
    self.driver.find_element(By.ID, "name").send_keys("Rathna")
    # 54 | click | id=proName | 
    self.driver.find_element(By.ID, "proName").click()
    # 55 | type | id=proName | Rathna Products
    self.driver.find_element(By.ID, "proName").send_keys("Rathna Products")
    # 56 | click | id=nic | 
    self.driver.find_element(By.ID, "nic").click()
    # 57 | type | id=nic | 123456789
    self.driver.find_element(By.ID, "nic").send_keys("123456789")
    # 58 | click | id=adderss | 
    self.driver.find_element(By.ID, "adderss").click()
    # 59 | type | id=adderss | Kaluthara
    self.driver.find_element(By.ID, "adderss").send_keys("Kaluthara")
    # 60 | click | id=contact | 
    self.driver.find_element(By.ID, "contact").click()
    # 61 | type | id=contact | 0710132681
    self.driver.find_element(By.ID, "contact").send_keys("0710132681")
    # 62 | click | css=.btn-default | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
    # 63 | click | css=tr:nth-child(2) button:nth-child(1) > a | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) button:nth-child(1) > a").click()
    # 64 | click | id=contact | 
    self.driver.find_element(By.ID, "contact").click()
    # 65 | click | id=contact | 
    self.driver.find_element(By.ID, "contact").click()
    # 66 | doubleClick | id=contact | 
    element = self.driver.find_element(By.ID, "contact")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 67 | type | id=contact | 0775586063
    self.driver.find_element(By.ID, "contact").send_keys("0775586063")
    # 68 | click | css=.btn-default | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-default").click()
  
